<a href="https://colab.research.google.com/github/Bharathjpv/Loan-Approval-Status/blob/main/Numpy_Tutorial_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x1 = np.array(['Intel', 'Microsoft'], dtype=np.str)
print("Array1:")
print(x1)

Array1:
['Intel' 'Microsoft']


In [3]:
x2 = np.array([' Google', ' IBM'], dtype=np.str)
print("Array2:")
print(x2)

Array2:
[' Google' ' IBM']


In [4]:
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)

new array:
['Intel Google' 'Microsoft IBM']


In [5]:
new_array = np.array(['Intel', 'Microsoft', 'Goggle', 'IBM'], dtype=np.str)
print("Original Array:")
print(new_array)

Original Array:
['Intel' 'Microsoft' 'Goggle' 'IBM']


In [6]:
capitalized_case = np.char.capitalize(new_array)
print("\nCapitalized: ", capitalized_case)


Capitalized:  ['Intel' 'Microsoft' 'Goggle' 'Ibm']


In [7]:
lowered_case = np.char.lower(new_array)
print("Lowered: ", lowered_case)

Lowered:  ['intel' 'microsoft' 'goggle' 'ibm']


In [8]:
uppered_case = np.char.upper(new_array)
print("Uppered: ", uppered_case)

Uppered:  ['INTEL' 'MICROSOFT' 'GOGGLE' 'IBM']


In [9]:
swapcased_case = np.char.swapcase(new_array)
print("Swapcased: ", swapcased_case)

Swapcased:  ['iNTEL' 'mICROSOFT' 'gOGGLE' 'ibm']


In [10]:
titlecased_case = np.char.title(new_array)
print("Titlecased: ", titlecased_case)

Titlecased:  ['Intel' 'Microsoft' 'Goggle' 'Ibm']


In [11]:
x = np.array(['Intel', 'Microsoft', 'Goggle', 'IBM'], dtype=np.str)
print("Original Array:")
print(x)

Original Array:
['Intel' 'Microsoft' 'Goggle' 'IBM']


In [12]:
print("Number of ‘i’:")
r = np.char.count(x, "i")
print(r)

Number of ‘i’:
[0 1 0 0]


In [13]:
print("count the lowest index of ‘I’:")
r = np.char.find(x, "I")
print(r)

count the lowest index of ‘I’:
[ 0 -1 -1  0]


In [14]:
print("Test if each element of the said array starts with 'I':")
r = np.char.startswith(x, "I")
print(r)

Test if each element of the said array starts with 'I':
[ True False False  True]


In [15]:
centered = np.char.center(x, 15, fillchar='_')
print("\nCentered =", centered)


Centered = ['_____Intel_____' '___Microsoft___' '_____Goggle____' '______IBM______']


In [16]:
left = np.char.ljust(x, 15, fillchar='_')
print("Left =", left)

Left = ['Intel__________' 'Microsoft______' 'Goggle_________' 'IBM____________']


In [17]:
right = np.char.rjust(x, 15, fillchar='_')
print("Right =", right)

Right = ['__________Intel' '______Microsoft' '_________Goggle' '____________IBM']


In [18]:
r = np.char.join("_", x)
print(r)

['I_n_t_e_l' 'M_i_c_r_o_s_o_f_t' 'G_o_g_g_l_e' 'I_B_M']


In [19]:
r = np.char.replace(x, "IBM", "Motorola")
print("\nNew array:")
print(r)


New array:
['Intel' 'Microsoft' 'Goggle' 'Motorola']


In [20]:
x1 = np.array(['IBM', 'Microsoft', 'Intel', 'Google', 'MHM'], dtype=np.str)
print("\nArray1:")
print(x1)


Array1:
['IBM' 'Microsoft' 'Intel' 'Google' 'MHM']


In [21]:
x2 = np.array(['ibm', 'Microsoft', 'Intel', 'Facebook', 'MHM'], dtype=np.str)
print("Array2:")
print(x2)

Array2:
['ibm' 'Microsoft' 'Intel' 'Facebook' 'MHM']


In [22]:
print("\nEqual test:")
r = np.char.equal(x1, x2)
print(r)


Equal test:
[False  True  True False  True]


In [23]:
print("\nNot equal test:")
r = np.char.not_equal(x1, x2)
print(r)


Not equal test:
[ True False False  True False]


In [24]:
# nppy.split()
# We are splitting the string
print(np.char.split('MHM Outcome based Education'))

['MHM', 'Outcome', 'based', 'Education']


In [25]:
# We are splitting the string
print(np.char.split('MHM, Outcome, based, Education', sep = ','))

['MHM', ' Outcome', ' based', ' Education']


In [26]:
# nppy.join()
# We are splitting the string
print(np.char.join('-', 'MHM'))

M-H-M


In [27]:
# We are splitting the string
print(np.char.join(['-', ':'], ['MHM']))

['M-H-M' 'M:H:M']


In [28]:
# nppy.count()
A=np.array(['MHM', 'Outcome', 'based', 'Education'])
# We are counting the substring
print(np.char.count(A,'MHM'))

[1 0 0 0]


In [29]:
# We are counting the substring
print(np.char.count(A, 'Out'))

[0 1 0 0]


In [30]:
# nppy.rfind()
# We are counting the substring
print(np.char.rfind(A,'MHM'))

[ 0 -1 -1 -1]


In [31]:
# We are counting the substring
print(np.char.rfind(A, 'Out'))

[-1  0 -1 -1]


In [32]:
# nppy.isnperic()
# We are counting the substring
print(np.char.isnumeric('123'))

True


In [33]:
# We are counting the substring
print(np.char.isnumeric('MHM'))

False


In [34]:
# nppy.equal()
# We are checking that strings are equal or not
A=np.char.equal('MHM', 'Education')
print(A)

False


In [35]:
# We are checking that strings are equal or not
A=np.char.equal('MHM', 'MHM')
print(A)

True
